#PMMPでマルチをするときのチーム分け用プラグイン
name: TeamColor
main: teamcolor\Main
version: 1.1.0
api: 3.0.0-ALPHA12
   
permissions:
 teamplugin.command:
  default: true
  description: 'Allows to join and leave teams, get information about team.'
  children:
   teamplugin.command:
    default: true
    description: 'Allows to join and leave teams, get information about team.'