#PMMPでマルチをするときのチーム分け用プラグイン
name: TeamColor
main: teamcolor\Main
version: 1.0.0
api: 3.0.0-ALPHA12

commands:
 team:
  description: 'チームに関する情報を確認できます'
  
 join:
  description: 'チームに参加します'
  
 leave:
  description: 'チームから抜けます'
   
permissions:
 teamplugin.command:
  default: true
  description: 'Allows to join and leave teams, get information about team.'
  children:
   teamplugin.command:
    default: true
    description: 'Allows to join and leave teams, get information about team.'